### ISSUE TITLE
Forbid read to open files beyond the script subtree

### ISSUE THREAD

**Issue by dlespiau** [jkcfg/jk#57]
It's worth trying to be as hermetic as possible ie. not allow reading random files on the system reading /etc/resolv.conf would make the script produce two different output on two different machines.

A way to prevent that would be to prevent std.read() from reaching anywhere but the subtree the script is located.

This could be an option of the read implementation, specified through `ExecuteOptions`.

**Comment by dlespiau** [comment]
This is now implemented:

```js
cat foo.js 
import * as std from '@jkcfg/std';

std.read('/etc/resolve.conf').then(t => std.log(t));
```

```console
$ jk run foo.js 
Promise rejected at undefined 0:0
Error: reads outside base path forbidden
    at recv (@jkcfg/std/internal/deferred.js:25:27)
    at requestAsPromise (@jkcfg/std/internal/deferred.js:73:34)
    at Module.read (@jkcfg/std/read.js:50:12)
    at foo.js:3:5
```
